global:
  scrape_interval: 15s  # как часто Prometheus запрашивает метрики (по умолчанию — 1m)
  evaluation_interval: 15s  # как часто Prometheus пересчитывает правила алертинга

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/__internal_metrics__'  # путь на FastAPI для сбора метрик
    static_configs:
      - targets: ['host.docker.internal:8000']  # если приложение крутится не в контейнере, а на хостовой машине
#      - targets: ['127.0.0.1:8000']  # где найти приложение (host:port), "app" = имя контейнера

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

#  - job_name: 'nginx_exporter'
#    static_configs:
#      - targets: ['nginx_exporter:9113']