services:

  db:
    image: &db-image postgres:18-alpine
    container_name: ${APP_NAME}__db
    hostname: ${APP_NAME}__db
    platform: linux/arm64
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data/
    command: >
      sh -c "exec docker-entrypoint.sh postgres &&
      psql -U ${DB_USERNAME} -d ${DB_DATABASE} -c 'ALTER DATABASE ${DB_DATABASE} REFRESH COLLATION VERSION;'"
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}
      interval: 5s
      timeout: 10s
      retries: 20

  db_test:
    image: *db-image
    container_name: ${APP_NAME}__db_test
    hostname: ${APP_NAME}__db_test
    platform: linux/arm64
    restart: unless-stopped
    # розширюємо кількість одночасних підключень до Postgres БД та кількість транзакцій. Важливо для комфортного запуску паралельних тестів.
    command: postgres -c 'max_connections=250' -c 'max_locks_per_transaction=128'
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    volumes:
      - /var/lib/postgresql/data

  mailer:
    image: axllent/mailpit:latest
    container_name: ${APP_NAME}__mailer
    hostname: ${APP_NAME}__mailer
    ports:
      - 8025:8025
      - 1025:1025


volumes:
  db_data:
    driver: local
    name: ${APP_NAME}_db_data