services:

  db:
    image: &db-image postgres:18-alpine
    container_name: ${APP_NAME}__db
    hostname: ${APP_NAME}__db
    platform: linux/arm64
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./logs/postgresql:/var/log/postgresql
      - ./infrastructures/postgresql/init-db:/docker-entrypoint-initdb.d
      - ./infrastructures/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}
      interval: 5s
      timeout: 10s
      retries: 20

  db_test:
    image: *db-image
    container_name: ${APP_NAME}__db_test
    hostname: ${APP_NAME}__db_test
    platform: linux/arm64
    restart: unless-stopped
    # розширюємо кількість одночасних підключень до Postgres БД та кількість транзакцій. Важливо для комфортного запуску паралельних тестів.
    command: postgres -c 'max_connections=250' -c 'max_locks_per_transaction=128'
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: ${APP_NAME}__rabbitmq
    hostname: ${APP_NAME}__rabbitmq
    platform: linux/arm64
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      # Проверяет, готов ли узел принимать подключения
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 10s     # Как часто проверять
      timeout: 5s       # Сколько ждать ответа
      retries: 5        # Сколько попыток до статуса "unhealthy"
      start_period: 15s # Время на "раскачку" после старта
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: ${APP_NAME}__redis
    hostname: ${APP_NAME}__redis
    platform: linux/arm64
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
#    command: redis-server --requirepass ${REDIS_PASSWORD} # раскомментировать если нужно чтоб пароль был обязательным
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 10s
      retries: 20

  mailer:
    image: axllent/mailpit:latest
    container_name: ${APP_NAME}__mailer
    hostname: ${APP_NAME}__mailer
    ports:
      - 8025:8025
      - 1025:1025

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: ${APP_NAME}__prometheus
    hostname: ${APP_NAME}__prometheus
    networks:
      default:
        aliases:
          - prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./infrastructures/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana:11.6.0
    container_name: ${APP_NAME}__grafana
    hostname: ${APP_NAME}__grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructures/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
#    ports:
#      - "9100:9100"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9100 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: ${APP_NAME}__postgres_exporter
    hostname: ${APP_NAME}__postgres_exporter
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/postgres?sslmode=disable
#    ports:
#      - "9187:9187"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9187 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  db_data:
    driver: local
    name: ${APP_NAME}_db_data
  redis_data:
    driver: local
    name: ${APP_NAME}_redis_data
  rabbitmq_data:
    driver: local
    name: ${APP_NAME}_rabbitmq_data
  grafana_data:
    driver: local
    name: ${APP_NAME}_grafana_data
  prometheus_data:
    driver: local
    name: ${APP_NAME}_prometheus_data